# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78ab695c61f697af10166e2910530877c9f80f2f1d2ed3fe3323309a2ba56e487e2d03f630de0fe81bf2d802d9b7227a62ef321fa31546d3a10059271ac3dfa1

test:
  secret_key_base: a3d225f709fa572776ad7011a90593ffe983273542cf5ec416c2f63327d02c7c653a34a20a339ff69a5f75e9aedde0c008269671c39319a0460936f521d876fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
